
version: "3.9"

services:
  # ai-api-self:
  #   build:
  #     context: ./ai-api
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8002:8000"
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock # Gives access from this container to control EVERYTHING :)
  #   environment:
  #     - TARGET_API=ai-api
  #     - TARGET_UI=ai-ui
  #     - TARGET_SELF_API=ai-api-self
  # ai-ui-self:
  #   build:
  #     context: ./ai-ui
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3002:3000"
  #   environment:
  #     - REACT_APP_API_URL=http://localhost:8002
  opencode-server:
    build:
      context: ./opencode-server
      dockerfile: Dockerfile
    ports:
      - 4096:4096    
    volumes:
      - ./opencode-server/opencode-config:/root/.config/opencode 
      - opencode_node_modules:/root/.config/opencode/node_modules 
      - ./ai-api:/merlin-ai/ai-api
      - ./api:/merlin-ai/api
      - ./ai-ui:/merlin-ai/ai-ui
      - ./ui:/merlin-ai/ui
  # ai-api:
  #   build:
  #     context: ./ai-api
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8001:8000"
  #   volumes:
  #     - ./ai-api:/app  # Mount the api folder into the container for hot refresh
  #     - /var/run/docker.sock:/var/run/docker.sock # Gives access from this container to control EVERYTHING :)
  # ai-ui:
  #   build:
  #     context: ./ai-ui
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3001:3000"
  #   environment:
  #      - WDS_SOCKET_PORT=3001
  #   volumes:
  #     - ./ai-ui:/app  # Mount the api folder into the container for hot refresh
  # git-controller:
  #   build:
  #     context: .
  #     dockerfile: ./git-controller/Dockerfile
  #   volumes:
  #     - .:/repo  # Mount the api folder into the container for hot refresh
 
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app  # Mount the api folder into the container for hot refresh
      - ~/.aws:/root/.aws:ro 
    environment:
      # Pass your host's AWS_PROFILE to the container, fallback to 'default' if not set
      - AWS_PROFILE=${AWS_PROFILE:-default} 
  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile # or Dockerfile_UI
    ports:
      - "3000:3000"
    volumes:
      - ./ui:/app                   # Mount all your code (for hot reload)
      - ui_node_modules:/app/node_modules # But overlay node_modules ONLY as a Docker volume
      - ~/.aws:/root/.aws:ro 
 
    environment:
      - NODE_ENV=development
      - AWS_PROFILE=${AWS_PROFILE:-default} 

    command: ["bun", "run", "dev", "--host", "0.0.0.0", "--port=3000"]

volumes:
  opencode_node_modules:
  ui_node_modules:
