[build]
  base = "ai-ui"  # The folder where your React app resides
  command = "npm run build"  # Command to build the React app (or `yarn build` if you're using yarn)
  publish = "ai-ui/build"  # The folder where the built files are outputted after running the build command

